import './globals.css'
import Header from "@/components/Header";

export const metadata = {
  title: 'Truc à troc',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <Header />        
      <body>
        {children}
      </body>
    </html>
  )
}
